name: saferoute
description: "Safe navigation app with real-time safety routes and SOS features."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    # HTTP & API
    dio: ^5.3.0
    http: ^1.0.0 # Updated to 1.0.0 for compatibility
    google_polyline_algorithm: ^3.1.0

    # Storage & Security
    flutter_secure_storage: ^9.2.0
    shared_preferences: ^2.2.0
    flutter_dotenv: ^6.0.0
    path_provider: ^2.1.5
    share_plus: ^12.0.1
    app_links: ^6.4.0

    # State Management
    provider: ^6.1.0

    # Maps & Location
    google_maps_flutter: ^2.5.0
    geolocator: ^14.0.0
    geocoding: ^2.2.0
    location: ^5.0.0
    flutter_compass: ^0.8.0

    # UI & Design
    google_fonts: ^6.1.0
    smooth_page_indicator: ^1.0.0
    card_swiper: ^3.0.0
    shimmer: ^3.0.0
    lottie: ^2.4.0
    animations: ^2.0.0
    flutter_svg: ^2.0.0
    badges: ^3.1.0

    # Utils
    intl: ^0.19.0
    uuid: ^4.0.0

    # Contacts
    flutter_contacts: ^1.1.9
    permission_handler: ^12.0.0

    # Sensors
    sensors_plus: ^7.0.0
    flutter_background_service: ^5.1.0
    flutter_background_service_android: ^6.3.0
    flutter_local_notifications: ^19.4.2

    # Image Picker
    image_picker: ^0.8.7

    # TTS
    flutter_tts: ^4.2.0

    # Local storage
    hive: ^2.2.3

    # OSM map
    flutter_map: ^8.2.1
    latlong2: ^0.9.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/fonts/
        - assets/map_types/
        - assets/animations/
        - assets/icons/
        - .env

    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Regular.ttf
              - asset: assets/fonts/Poppins-Bold.ttf
                weight: 700
              - asset: assets/fonts/Poppins-SemiBold.ttf
                weight: 600
        - family: Inter
          fonts:
              - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
              - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
                weight: 700
              - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
                weight: 600
